VIR-20: Mass changes
virkarekisteri/virkarekisteri pull request #56
Opened 2024-12-10 21:09 UTC by Lassi2k

* Mass changes work with the history
* Added the modal and setupping the view
* User can now choose as many as many position as needed
* The latest clicked will be open in position details view even if it
  was unopened. This works fine as it will still close if none are open
* Handle the passing of the selected positions to mass changes modal
* Fix to use local time

2024-12-10 21:16 UTC, Lassi2k commented
![kuva](https://github.com/user-attachments/assets/fbf54c29-7822-42fc-90fb-d424f31f1847)

![kuva](https://github.com/user-attachments/assets/4467cc5a-df7f-4dbc-92f0-7bba97941a16)

![kuva](https://github.com/user-attachments/assets/014f5d07-d9b5-4657-b5ef-9ee906df8542)

![kuva](https://github.com/user-attachments/assets/73126027-9b04-47d8-b41e-a7282715777d)

2024-12-10 21:18 UTC, Peskarhu commented
Whats up with those ESLint errors? I tried to fix those but was too tired today so if you have any tips

2024-12-10 22:41 UTC, Lassi2k commented
Also made some UI smoothings, but I will add those later:

![kuva](https://github.com/user-attachments/assets/85db3007-6ea8-43e2-8f9a-6ee17b31d65c)

2024-12-11 00:32 UTC, 0x464e requested changes, later dismissed

2024-12-11 00:32 UTC, 0x464e commented on backend/Virkarekisteri/src/Repositories/ChangeLogRepository.cs
> +        changeLogEntry.Timestamp = DateTime.UtcNow.ToLocalTime();
What timezone might this "local time" be on the server which happens to run this. Not sure how it works, but I think we should explicitly specify a timezone.

2024-12-11 00:42 UTC, 0x464e commented on backend/Virkarekisteri/src/Repositories/ChangeLogRepository.cs
> +        changeLogEntry.Timestamp = DateTime.UtcNow.ToLocalTime();
Ok, actually I just set a setting in azure which I believe makes the function app's time zone be our time zone.

2024-12-11 21:23 UTC, niinakos commented
Did some testing, seems to work well! Good job. Although decision details field should be removed as what was discussed.

2024-12-11 21:59 UTC, Lassi2k commented
Made some final modifyings: 
![kuva](https://github.com/user-attachments/assets/4aee4860-5537-4554-8fc3-2aed86c836e4)

2024-12-12 11:44 UTC, 0x464e approved these changes
Good job! Works nicely

2024-12-12 11:47 UTC, merged