Vir 31 update position
virkarekisteri/virkarekisteri pull request #7
Opened 2024-10-10 19:00 UTC by joonasyr

- Added DTO model which containts fields that can be updated for the Position model
- Created UpdatePosition function which handles HTTP PUT requests to update an existing position with id
- Implemented the UpdatePosition method within the PositionRepository which uses Entity Framework no mark entry as modified and save it to database

UpdatePosition can be expanded in the future to support fields in addition to PaattymisPvm and LopetusPaatosNumero

https://tuni-team-hvtovuq0.atlassian.net/jira/software/projects/VIR/boards/1/backlog?selectedIssue=VIR-31

2024-10-11 09:16 UTC, joonasyr commented
Tested with the following curl format:

$uri = "http://localhost:7071/api/positions/ID"  # Replace with your ID
$body = '{"PaattymisPvm": "2024-11-10T00:00:00Z", "LopetusPaatosNumero": "9876543210}' # Replace values with your own
$headers = @{ "Content-Type" = "application/json" }
Invoke-RestMethod -Uri $uri -Method Put -Body $body -Headers $headers

2024-10-13 21:04 UTC, 0x464e requested changes
Looks good apart from the minor things I commented

2024-10-13 21:04 UTC, 0x464e commented on backend/src/Functions/Positions/UpdatePosition.cs
> +    public UpdatePosition(ILogger<UpdatePosition> logger, PositionRepository positionRepository)
We can use primary constructor here for cleaner/less boilerplate. For an example see e.g. https://github.com/virkarekisteri/virkarekisteri/blob/fcc57a7ae3eace9669fc1b4c3d818c5b349aeba2/backend/src/Functions/Positions/CreatePosition.cs#L11

2024-10-13 21:04 UTC, 0x464e commented on backend/src/Repositories/PositionRepository.cs
> +    /// <param name="position">The Position object containing updated values to save.</param>
Out of date param name in XML comment

2024-10-13 21:04 UTC, 0x464e commented on backend/src/Models/UpdatePositionDto.cs
> +namespace Virkarekisteri.Models
Should we separate DTOs to a different folder from the EF models?

2024-10-13 21:04 UTC, 0x464e commented on backend/src/Models/UpdatePositionDto.cs
> +        public DateTime? PaattymisPvm { get; set; }
Lets use English. Use the same names as in the Position model

2024-10-14 16:08 UTC, joonasyr commented on backend/src/Models/UpdatePositionDto.cs
> +namespace Virkarekisteri.Models
Can be restructured later on if seen feasible.

2024-10-14 16:16 UTC, joonasyr commented
After switching to english, the body of the request has to be in English as well. Here my curl for testing:

$uri = "http://localhost:7071/api/positions/id"  # Replace with your ID
$body = '{"EndedAt": "2020-11-10T00:00:00Z", "EndingDecisionNumber": "11111111"}'
$headers = @{ "Content-Type" = "application/json" }

Invoke-RestMethod -Uri $uri -Method Put -Body $body -Headers $headers

2024-10-14 17:39 UTC, 0x464e approved these changes

2024-10-14 17:53 UTC, 0x464e commented
> After switching to english, the body of the request has to be in English as well. Here my curl for testing:
> 
> $uri = "http://localhost:7071/api/positions/id" # Replace with your ID $body = '{"EndedAt": "2020-11-10T00:00:00Z", "EndingDecisionNumber": "11111111"}' $headers = @{ "Content-Type" = "application/json" }
> 
> Invoke-RestMethod -Uri $uri -Method Put -Body $body -Headers $headers

As a tip, you can also conveniently use your IDEs HTTP client to send requests more conveniently.  

E.g. in Rider you can also quickly access it with:  
![image](https://github.com/user-attachments/assets/0475f99b-eeb9-4219-9f9e-f285c26d238d)

2024-10-15 14:20 UTC, merged